### PR TITLE
Add newline on file ends

### PR DESCRIPTION
**Pull request by TheDevMinerTV**

### CODE REVIEW

**Comment by Savjee** [comment]
Thanks! Eslint is now however throwing some errors. Can you configure eslint so it accepts these blank lines? (See Travis error)

**Comment by TheDevMinerTV** [comment]
Oh i know...
I probably hugged it up and i places spaces after the newline.

Sorry!

**Comment by TheDevMinerTV** [comment]
Done! :smile: :+1:

Finally fixed!

**Comment by Savjee** [comment]
Thanks!

**Pull request merged**
